### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by xiaobinzero** [robotics-upo/lightpomcp#1]
Hi there. It is an awesome package. Currently, there are some compilation errors. Basically, in the main functions for `tag.cpp` and `tiger.cpp`, the class initialization for `PomcpPlanner` requires 6 arguments but both of them are given 4. I think `resamplingTimeout` and `aparticlesInitialBelief` are missing. Could you please add the values for these two examples? 

Thanks!

**Comment by Ignacio-Perez** [comment]
Thank you! We have fixed the bug in the last commit.
